### ISSUE TITLE
Periods in the track name truncate the final filename

### ISSUE THREAD

**Issue by alextarrell** [MinisculeGirraffe/tdl#22]
Filenames are getting truncated after the first period. The logs indicate that internally the tracks are being parsed properly, so it's likely breaking when it goes to assemble the final filename.

[Here's](https://listen.tidal.com/album/234385776) an example album.

This is what the first track from that album ends up being saved as:
```
1-1 - It looks like scarlet devil -LNBBC Remix-(feat.flac
```

Here's what that same track is being logged as:
```
[1] Hachimitsu-Lemon - It looks like scarlet devil -LNBBC Remix-(feat.Mitsuki Nakae)
```

Here's the relevant section from my local config:
```toml
[download_paths]
base_path = '$HOME/Music'
artist = ''
album = '{album_name} [{album_quality}-{album_id}] [{album_release_year}] ({album_tracks})'
track = '{track_volume}-{track_num} - {track_name} - {artist_name} [{track_id}]'
```
